server:
  port: 0
  servlet:
    context-patch: /client-crud
spring:
  application:
    name: client-crud

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: secret
    url: jdbc:mysql://localhost:3306/clients
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

