server:
  port: 7777

spring:
  application:
    name: config-server

  profile: default

  cloud:
    config:
      server:
        git:
          uri: https://github.com/daniel1jorge/spring-cloud-config.git
          default-label: main
          clone-on-start: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/